### ISSUE TITLE
Extend the proxy to provide RateLimit headers

### ISSUE THREAD

**Issue by jansenbe** [microsoftgraph/msgraph-developer-proxy#55] opened 2022-12-02 10:09 UTC
SharePoint API calls (Graph, REST, CSOM) return [RateLimit headers](https://github.com/ietf-wg-httpapi/ratelimit-headers) whenever the application is about the consume its resource unit quota (see https://aka.ms/sharepoint/throttling). It would be good if the proxy allowed to mimic that by allowing the user to set the resource unit quota and then the proxy can track the request coming in, calculate the resource units for the request and verify if the quota is about to expire...if so, the proxy can start to include rate limit headers in the response.

.NET 7 has support for tracking and applying rate limits, see https://devblogs.microsoft.com/dotnet/announcing-rate-limiting-for-dotnet/

**Comment by waldekmastykarz** [comment] 2022-12-02 16:39
This would be a great addition to use the new functionality and help developers test how their application is backing off when it starts getting rate limiting information.

@gavinbarron what do you think would be the best way to implement this?

**Comment by gavinbarron** [comment] 2022-12-02 21:11
@jansenbe thanks for that info on the rate limiting, that's going to be very helpful!
AFAIK the resource unit concept of rate limiting also applies to the SPO apis that are exposed via Graph and it's a scenario we would need to account for sooner or later.

On the implementation question, I think we need to sit down and look at how we can break apart the traffic handing to allow for some kind of middleware setup which might allow for a plug-in style of extension to the tool where a plug-in might define the rate limiting behavior. 

This could allow for complex configuration via config for the middleware while still providing an option for some lightweight usage scenarios for primitive failures etc as we currently provide.

**Comment by waldekmastykarz** [comment] 2022-12-04 16:41
@gavinbarron could the first implementation become a part of our behaviors work along with other service limits? In the long run we could allow for more flexibility through plugins. What do you think?

**Comment by gavinbarron** [comment] 2022-12-05 18:29
@waldekmastykarz yes! That's where my thoughts were going with this one.

**Comment by waldekmastykarz** [comment] 2023-03-27 11:12
Duplicate of #210. We'll close this issue and track work status using #210 which is linked to the PR

**Closed by waldekmastykarz** 2023-03-27 11:12 UTC
Labels: enhancement, needs spec
